function parse_psydats(inp)

% Input variables
%   ert_psydat_csv
%   rift_psydat_csv
%   out_dir


%% ERT - Get timing info from converted psydat
warning('off','MATLAB:table:ModifiedAndSavedVarnames');
timings_ert = readtable(inp.ert_psydat_csv);

% Add condition column
timings_ert.ACTUAL_CONDITION = strcat(timings_ert.image_category,'_',timings_ert.strategy);

% Condition and timing variables
keepvars = { ...
    'block_file', ...
    'image_category', ...
    'strategy', ...
    'image_filename', ...
    'instructional_cue_started', ...
    'instructional_cue_stopped', ...
    'image_started', ...
    'image_stopped', ...
    'affect_rating_ert_started', ...
    'affect_rating_ert_stopped' ...
    };

% Find scan start times. startedScanning has inconsistent/unknown value in
% some cases so don't use it
scanstarts = sort(timings_ert.wait_for_scanner_stopped(~isnan(timings_ert.wait_for_scanner_stopped)));

% Run-specific timing info relative to beginning of first fmri
clear trialtimes_ert
nruns = 2;
for r = 1:nruns
    blockfile = ['ert_block_' num2str(r) '.csv'];
    trialtimes_ert{r} = timings_ert(strcmp(timings_ert.block_file,blockfile),keepvars);
    %trialtimes_ert{r}(:,timevars) = trialtimes_ert{r}(:,timevars) - scanstarts(r);
    trialtimes_ert{r}.TRIAL_TYPE_ERT(:) = {'ERT'};
    trialtimes_ert{r}.TRIAL_TYPE_RIFT(:) = {''};
    trialtimes_ert{r}.SCAN_START(:) = scanstarts(r);
    trialtimes_ert{r}.RUN(:) = {['ERT_' num2str(r)]};

    trialtimes_ert{r}.ACTUAL_CONDITION = strcat(trialtimes_ert{r}.image_category,'_',trialtimes_ert{r}.strategy);

    trialtimes_ert{r}.CUE_ONSET = trialtimes_ert{r}.instructional_cue_started - trialtimes_ert{r}.SCAN_START;
    trialtimes_ert{r}.CUE_DURATION = trialtimes_ert{r}.instructional_cue_stopped - trialtimes_ert{r}.instructional_cue_started;
        
    trialtimes_ert{r}.IMAGE_ONSET = trialtimes_ert{r}.image_started - trialtimes_ert{r}.SCAN_START;
    trialtimes_ert{r}.IMAGE_DURATION = trialtimes_ert{r}.image_stopped - trialtimes_ert{r}.image_started;

    trialtimes_ert{r}.RATING_ONSET = trialtimes_ert{r}.affect_rating_ert_started - trialtimes_ert{r}.SCAN_START;
    trialtimes_ert{r}.RATING_DURATION = trialtimes_ert{r}.affect_rating_ert_stopped - trialtimes_ert{r}.affect_rating_ert_started;

    trialtimes_ert{r} = trialtimes_ert{r}(:, { ...
        'block_file', ...
        'image_category', ...
        'strategy', ...
        'image_filename', ...
        'instructional_cue_started', ...
        'instructional_cue_stopped', ...
        'image_started', ...
        'image_stopped', ...
        'affect_rating_ert_started', ...
        'affect_rating_ert_stopped', ...
        'RUN', ...
        'SCAN_START', ...
        'TRIAL_TYPE_ERT', ...
        'TRIAL_TYPE_RIFT', ...
        'ACTUAL_CONDITION', ...
        'CUE_ONSET', ...
        'CUE_DURATION', ...
        'IMAGE_ONSET', ...
        'IMAGE_DURATION', ...
        'RATING_ONSET', ...
        'RATING_DURATION' ...
        });
end


%% RIFT - Get timing info from converted psydat
timings_rift = readtable(inp.rift_psydat_csv);

% Condition and timing variables
keepvars = { ...
    'block_file', ...
    'image_category', ...
    'strategy', ...
    'switched', ...
    'new_strategy_chosen', ...
    'image_filename' ...
    'instructional_cue_rift_started', ...
    'instructional_cue_rift_stopped', ...
    'image_2_started', ...
    'image_2_stopped', ...
    'affect_rating_rift_started', ...
    'affect_rating_rift_stopped' ...
    };

% Find scan start times. startedScanning has inconsistent/unknown value in
% some cases so don't use it
scanstarts = sort(timings_rift.wait_for_scanner_stopped(~isnan(timings_rift.wait_for_scanner_stopped)));

% Run-specific timing info relative to beginning of first fmri
clear trialtimes_rift
nruns = 4;
for r = 1:nruns
    blockfile = ['rift_block_' num2str(r) '.csv'];
    trialtimes_rift{r} = timings_rift(strcmp(timings_rift.block_file,blockfile),keepvars);
    trialtimes_rift{r}.SCAN_START(:) = scanstarts(r);
    trialtimes_rift{r}.RUN(:) = {['RIFT_' num2str(r)]};

    % new_strategy_chosen only makes sense if they switched (otherwise is
    % historical)
    trialtimes_rift{r}.new_strategy_chosen(~strcmp(trialtimes_rift{r}.switched,'yes')) = {''};

    % Some trials get two rows, but only one row has timing info
    trialtimes_rift{r} = trialtimes_rift{r}(~isnan(trialtimes_rift{r}.instructional_cue_rift_started),:);

    % If image is repeated, it is the second trial of a RIFT pair, so let's
    % make a temporary shifted comparison variable
    trialtimes_rift{r}.shifted_filename(:) = {''};
    trialtimes_rift{r}.shifted_filename(2:end) = trialtimes_rift{r}.image_filename(1:end-1);

    % Default to no label
    trialtimes_rift{r}.TRIAL_TYPE_RIFT(:) = {''};

    % Second trial of RIFT pair labeled RIFT2
    trialtimes_rift{r}.TRIAL_TYPE_RIFT(strcmp(trialtimes_rift{r}.image_filename,trialtimes_rift{r}.shifted_filename)) = {'RIFT2'};

    % Anything before a RIFT2 is a RIFT1
    r2 = find(strcmp(trialtimes_rift{r}.TRIAL_TYPE_RIFT,'RIFT2'));
    trialtimes_rift{r}.TRIAL_TYPE_RIFT(r2-1) = {'RIFT1'};

    % Unlabeled and RIFT1 are also used for ERT
    trialtimes_rift{r}.TRIAL_TYPE_ERT(:) = {'ERT'};
    trialtimes_rift{r}.TRIAL_TYPE_ERT(strcmp(trialtimes_rift{r}.TRIAL_TYPE_RIFT,'RIFT2')) = {''};

    % Fix condition labels
    trialtimes_rift{r}.ACTUAL_CONDITION = strcat(trialtimes_rift{r}.image_category,'_',trialtimes_rift{r}.strategy);
    update_conds = find(strcmp(trialtimes_rift{r}.switched,'yes')) + 1;
    trialtimes_rift{r}.ACTUAL_CONDITION(update_conds) = ...
        strcat( ...
        trialtimes_rift{r}.image_category(update_conds), ...
        '_', ...
        trialtimes_rift{r}.new_strategy_chosen(update_conds-1) ...
        );

    trialtimes_rift{r}.CUE_ONSET = trialtimes_rift{r}.instructional_cue_rift_started - trialtimes_rift{r}.SCAN_START;
    trialtimes_rift{r}.CUE_DURATION = trialtimes_rift{r}.instructional_cue_rift_stopped - trialtimes_rift{r}.instructional_cue_rift_started;
        
    trialtimes_rift{r}.IMAGE_ONSET = trialtimes_rift{r}.image_2_started - trialtimes_rift{r}.SCAN_START;
    trialtimes_rift{r}.IMAGE_DURATION = trialtimes_rift{r}.image_2_stopped - trialtimes_rift{r}.image_2_started;

    trialtimes_rift{r}.RATING_ONSET = trialtimes_rift{r}.affect_rating_rift_started - trialtimes_rift{r}.SCAN_START;
    trialtimes_rift{r}.RATING_DURATION = trialtimes_rift{r}.affect_rating_rift_stopped - trialtimes_rift{r}.affect_rating_rift_started;


    % FIXME also label RIFT trials as these (which should be all the
    % possibilities):
    %    RtoA_1, RtoA_2
    %    AtoR_1, AtoR_2
    %    RtoR_1, RtoR_2
    %    AtoA_1, AtoA_2
    %
    % Or just as RtoA, AtoR, RtoR, AtoA ?
    

    trialtimes_rift{r} = trialtimes_rift{r}(:, { ...
        'block_file', ...
        'image_category', ...
        'strategy', ...
        'new_strategy_chosen', ...
        'image_filename', ...
        'switched', ...
        'instructional_cue_rift_started', ...
        'instructional_cue_rift_stopped', ...
        'image_2_started', ...
        'image_2_stopped', ...
        'affect_rating_rift_started', ...
        'affect_rating_rift_stopped', ...
        'RUN', ...
        'SCAN_START', ...
        'TRIAL_TYPE_ERT', ...
        'TRIAL_TYPE_RIFT', ...
        'ACTUAL_CONDITION', ...
        'CUE_ONSET', ...
        'CUE_DURATION', ...
        'IMAGE_ONSET', ...
        'IMAGE_DURATION', ...
        'RATING_ONSET', ...
        'RATING_DURATION' ...
        });

end

