
inp = struct( ...
    'hpf_sec', '300', ...
    'fwhm_mm', '6', ...
    'ert_psydat_csv', '../../OUTPUTS/ert1.csv', ...
    'rift_psydat_csv', '../../OUTPUTS/rift1.csv', ...
    'fmriprep_ert1_dir', '../../INPUTS/fmriprep-ert1/fmriprepBIDS', ...
    'fmriprep_ert2_dir', '../../INPUTS/fmriprep-ert2/fmriprepBIDS', ...
    'fmriprep_rift1_dir', '../../INPUTS/fmriprep-rift1/fmriprepBIDS', ...
    'fmriprep_rift2_dir', '../../INPUTS/fmriprep-rift2/fmriprepBIDS', ...
    'fmriprep_rift3_dir', '../../INPUTS/fmriprep-rift3/fmriprepBIDS', ...
    'fmriprep_rift4_dir', '../../INPUTS/fmriprep-rift4/fmriprepBIDS', ...
	'out_dir', '../../OUTPUTS' ...
	);

outp = fileprep_ert_rift(inp);

%%
first_level_stats_ert(outp);

