
inp = struct( ...
    'hpf_sec', '300', ...
    'fwhm_mm', '6', ...
    'ert_psydat_csv', '../../OUTPUTS/ert1.csv', ...
    'rift_psydat_csv', '../../OUTPUTS/rift1.csv', ...
    'fmriprep1_dir', '../../INPUTS/fmriprep-ert1', ...
    'fmriprep2_dir', '../../INPUTS/fmriprep-ert2', ...
	'out_dir', '../../OUTPUTS' ...
	);

first_level_stats_ert_rift(inp);

